import type {
  DatasetCatalogEntry,
  DomainCatalogEntry,
  KnowledgeCatalogEntry,
  ModalityCatalogEntry,
  TaskCatalogEntry,
} from './contracts';

export const domainCatalog: DomainCatalogEntry[] = [
  {
    id: 'dom-medical',
    title: 'Medical clinical table for patient safety and outcome prediction',
    shortDescription:
      'Patient or visit level tables with vitals, labs, drug exposure, and safety or outcome labels.',
    keywords: ['patient', 'visit', 'clinical', 'hospital', 'drug', 'adverse', 'vital', 'lab'],
    aliases: ['clinical outcomes', 'medical safety', 'patient outcome prediction'],
    strongSignals: ['patient', 'clinical', 'hospital', 'drug', 'adverse', 'diagnosis', 'vital', 'lab'],
    supportSignals: ['visit', 'trial', 'medication', 'biomarker'],
    negativeSignals: ['authorship', 'generated', 'prompt', 'content', 'language', 'topic', 'essay'],
    modality: 'table',
    querySeeds: ['clinical outcome prediction table', 'patient safety classification dataset'],
    reasonTemplate: 'Clinical patient-level signals, visit context, and safety labels suggest a medical table domain.',
  },
  {
    id: 'dom-bio',
    title: 'Life science laboratory table for biomarker driven classification',
    shortDescription:
      'Assay, specimen, biomarker, or omics tables used for disease state or treatment response analysis.',
    keywords: ['biomarker', 'assay', 'specimen', 'protein', 'gene', 'omics', 'batch', 'lab'],
    aliases: ['bioscience', 'omics assay', 'biomarker classification'],
    strongSignals: ['biomarker', 'assay', 'specimen', 'protein', 'gene', 'omics'],
    supportSignals: ['batch', 'lab', 'sample'],
    negativeSignals: ['authorship', 'generated', 'prompt', 'content', 'topic', 'language'],
    modality: 'table',
    querySeeds: ['biomarker classification benchmark', 'omics assay response dataset'],
    reasonTemplate: 'Assay or biomarker-oriented measurements align with a life science laboratory table.',
  },
  {
    id: 'dom-finance',
    title: 'Financial market or transaction dataset for risk detection and forecasting',
    shortDescription:
      'Financial tables spanning transaction risk data as well as market price history, OHLCV, and technical indicators.',
    keywords: [
      'transaction',
      'account',
      'payment',
      'merchant',
      'fraud',
      'stock',
      'market',
      'ohlcv',
      'price',
      'return',
      'volatility',
      'rsi',
      'macd',
    ],
    aliases: ['fraud detection', 'financial anomaly', 'transaction risk', 'stock forecasting', 'market time series'],
    strongSignals: [
      'transaction',
      'account',
      'payment',
      'merchant',
      'fraud',
      'chargeback',
      'card',
      'stock',
      'market',
      'ohlcv',
      'price',
      'close',
      'open',
      'high',
      'low',
      'return',
      'volatility',
      'rsi',
      'macd',
    ],
    supportSignals: ['amount', 'transfer', 'identity', 'risk', 'volume', 'forecast', 'time series'],
    negativeSignals: ['prompt', 'content', 'language', 'essay', 'clinical', 'patient'],
    modality: 'table',
    querySeeds: [
      'transaction fraud detection table',
      'financial anomaly benchmark dataset',
      'historical stock price forecasting dataset',
      'OHLCV time series regression data',
    ],
    reasonTemplate: 'Financial market indicators or transaction risk signals indicate a finance-oriented dataset.',
  },
  {
    id: 'dom-industrial',
    title: 'Industrial sensor table for process and equipment monitoring',
    shortDescription:
      'Sensor driven process tables with temperature, pressure, vibration, or machine telemetry.',
    keywords: ['sensor', 'machine', 'equipment', 'vibration', 'temperature', 'pressure', 'rpm'],
    aliases: ['predictive maintenance', 'process monitoring', 'equipment telemetry'],
    strongSignals: ['sensor', 'machine', 'equipment', 'vibration', 'temperature', 'pressure', 'rpm'],
    supportSignals: ['telemetry', 'failure', 'maintenance'],
    negativeSignals: ['prompt', 'content', 'topic', 'language', 'essay', 'fraud'],
    modality: 'table',
    querySeeds: ['predictive maintenance sensor dataset', 'industrial telemetry anomaly table'],
    reasonTemplate: 'Telemetry and sensor measurements fit an industrial monitoring dataset.',
  },
  {
    id: 'dom-environment',
    title: 'Environmental monitoring table for threshold breach detection',
    shortDescription:
      'Station or region level tables containing air, water, weather, or pollution observations.',
    keywords: ['air', 'water', 'weather', 'station', 'pollution', 'pm25', 'monitoring'],
    aliases: ['environmental sensing', 'air quality monitoring', 'water quality table'],
    strongSignals: ['air', 'water', 'weather', 'station', 'pollution', 'pm25'],
    supportSignals: ['monitoring', 'sensor', 'region'],
    negativeSignals: ['prompt', 'content', 'authorship', 'generated', 'fraud'],
    modality: 'table',
    querySeeds: ['air quality monitoring table', 'water quality threshold dataset'],
    reasonTemplate: 'Station or environmental observation signals match a monitoring table.',
  },
  {
    id: 'dom-public',
    title: 'Public sector table for regional or agency level risk prediction',
    shortDescription:
      'Administrative, demographic, or policy indicator tables used for public sector analytics.',
    keywords: ['region', 'city', 'district', 'policy', 'population', 'public', 'agency'],
    aliases: ['public administration analytics', 'regional policy scoring'],
    strongSignals: ['region', 'district', 'agency', 'policy', 'public'],
    supportSignals: ['city', 'population', 'administrative'],
    negativeSignals: ['prompt', 'content', 'generated', 'authorship', 'biomarker'],
    modality: 'table',
    querySeeds: ['public sector risk table', 'regional policy indicator dataset'],
    reasonTemplate: 'Regional or agency-level administrative indicators suggest a public sector table.',
  },
  {
    id: 'dom-nlp',
    title: 'Natural language processing dataset for text understanding tasks',
    shortDescription:
      'Text-heavy datasets containing prompts, documents, passages, or responses for classification or retrieval.',
    keywords: ['text', 'language', 'document', 'prompt', 'content', 'sentence', 'response', 'question'],
    aliases: ['nlp', 'natural language processing', 'text corpus'],
    strongSignals: ['text', 'prompt', 'content', 'language', 'document', 'sentence', 'response'],
    supportSignals: ['topic', 'source', 'review', 'comment', 'transcript'],
    negativeSignals: ['patient', 'biomarker', 'transaction', 'sensor', 'turbofan'],
    modality: 'text',
    querySeeds: ['natural language processing classification dataset', 'text corpus with prompts and labels'],
    reasonTemplate: 'Prompt, content, and language-oriented columns indicate a text-centric NLP dataset.',
  },
  {
    id: 'dom-text-classification',
    title: 'Text classification dataset with labeled documents or responses',
    shortDescription:
      'Labeled text, prompt, review, or article datasets for supervised content classification.',
    keywords: ['text classification', 'document label', 'content label', 'topic classification', 'language feature'],
    aliases: ['document classification', 'content classification', 'labeled text'],
    strongSignals: ['text', 'content', 'prompt', 'label', 'topic', 'language', 'document'],
    supportSignals: ['word_count', 'char_count', 'complexity', 'review', 'comment'],
    negativeSignals: ['patient', 'merchant', 'vibration', 'pm25'],
    modality: 'text',
    querySeeds: [
      'text classification dataset with metadata',
      'labeled content classification benchmark',
      'prompt and response text classification corpus',
    ],
    reasonTemplate: 'Labeled text fields with language or topic metadata fit a text classification dataset.',
  },
  {
    id: 'dom-content-authenticity',
    title: 'Content authenticity and provenance dataset',
    shortDescription:
      'Datasets focused on authenticity, provenance, or trustworthiness of written or generated content.',
    keywords: ['authenticity', 'provenance', 'trust', 'source', 'generated', 'human', 'machine'],
    aliases: ['content provenance', 'text authenticity', 'provenance analysis'],
    strongSignals: ['authenticity', 'provenance', 'generated', 'human', 'machine', 'source'],
    supportSignals: ['topic', 'language', 'style', 'metadata'],
    negativeSignals: ['patient', 'transaction', 'turbofan', 'pollution'],
    modality: 'text',
    querySeeds: [
      'content authenticity classification dataset',
      'text provenance benchmark with metadata',
      'generated versus human content authenticity dataset',
    ],
    reasonTemplate: 'Authenticity, provenance, and source-aware content signals match a content authenticity domain.',
  },
  {
    id: 'dom-ai-generated-content-detection',
    title: 'AI-generated content detection dataset',
    shortDescription:
      'Benchmarks for distinguishing human-written content from AI-generated or machine-assisted text.',
    keywords: ['ai generated', 'human written', 'machine written', 'gpt', 'llm', 'ai_model', 'synthetic text'],
    aliases: ['ai vs human text classification', 'generated text detection', 'machine written detection'],
    strongSignals: ['ai', 'human', 'generated', 'machine', 'llm', 'gpt', 'ai_model'],
    supportSignals: ['prompt', 'content', 'source', 'topic', 'language', 'word_count'],
    negativeSignals: ['patient', 'merchant', 'vibration', 'weather'],
    modality: 'text',
    querySeeds: [
      'AI vs human generated text classification dataset',
      'generated content detection benchmark with prompts',
      'human versus machine written content detection dataset',
    ],
    reasonTemplate: 'AI-vs-human labels with prompt/content fields directly align with generated content detection.',
  },
  {
    id: 'dom-authorship-attribution',
    title: 'Authorship attribution and writing style analysis dataset',
    shortDescription:
      'Corpora used to attribute authorship, identify stylistic signatures, or analyze writing behavior.',
    keywords: ['authorship', 'author', 'writing style', 'stylistic', 'writer', 'linguistic signature'],
    aliases: ['author identification', 'writing style analysis', 'author attribution'],
    strongSignals: ['authorship', 'author', 'writer', 'style', 'writing', 'language'],
    supportSignals: ['prompt', 'content', 'topic', 'word_count', 'complexity'],
    negativeSignals: ['patient', 'merchant', 'sensor', 'pollution'],
    modality: 'text',
    querySeeds: [
      'authorship attribution benchmark corpus',
      'writing style analysis dataset with prompts',
      'author identification text classification dataset',
    ],
    reasonTemplate: 'Writing style and authorship cues suggest an authorship attribution dataset.',
  },
  {
    id: 'dom-media-forensics',
    title: 'Media forensics and synthetic content analysis dataset',
    shortDescription:
      'Datasets for detecting synthetic, manipulated, or machine-generated media or text artifacts.',
    keywords: ['forensics', 'synthetic', 'generated', 'manipulated', 'artifact', 'detector'],
    aliases: ['synthetic content forensics', 'media authenticity', 'tamper detection'],
    strongSignals: ['synthetic', 'generated', 'forensics', 'manipulated', 'artifact'],
    supportSignals: ['source', 'provenance', 'prompt', 'content'],
    negativeSignals: ['patient', 'merchant', 'sensor'],
    modality: 'hybrid',
    querySeeds: [
      'synthetic content forensics benchmark',
      'generated text artifact detection dataset',
      'media authenticity benchmark corpus',
    ],
    reasonTemplate: 'Synthetic or manipulated content cues fit a media forensics style benchmark.',
  },
  {
    id: 'dom-misinformation-provenance',
    title: 'Misinformation and provenance analysis dataset',
    shortDescription:
      'Datasets for source credibility, provenance tracking, claim verification, or misinformation detection.',
    keywords: ['misinformation', 'provenance', 'source credibility', 'claim', 'fact check', 'news'],
    aliases: ['fact checking', 'source credibility', 'provenance detection'],
    strongSignals: ['misinformation', 'provenance', 'source', 'claim', 'credibility'],
    supportSignals: ['topic', 'language', 'article', 'content'],
    negativeSignals: ['patient', 'fraud', 'sensor'],
    modality: 'text',
    querySeeds: [
      'misinformation detection dataset with source metadata',
      'text provenance and source credibility benchmark',
      'claim verification corpus with topic and language',
    ],
    reasonTemplate: 'Source and provenance-oriented text signals point to misinformation or provenance analysis.',
  },
  {
    id: 'dom-education-writing-analysis',
    title: 'Education writing analysis and rubric-driven text dataset',
    shortDescription:
      'Writing samples, essays, or prompt-response corpora used for educational writing analysis.',
    keywords: ['essay', 'student writing', 'prompt response', 'rubric', 'writing quality', 'composition'],
    aliases: ['essay scoring', 'student writing analysis', 'writing rubric dataset'],
    strongSignals: ['essay', 'student', 'writing', 'prompt', 'response', 'rubric'],
    supportSignals: ['language', 'topic', 'word_count', 'complexity'],
    negativeSignals: ['patient', 'merchant', 'sensor'],
    modality: 'text',
    querySeeds: [
      'student writing analysis dataset',
      'prompt response authenticity dataset',
      'essay writing benchmark with rubric features',
    ],
    reasonTemplate: 'Prompt-response structure and writing-quality features match an education writing dataset.',
  },
];

export const taskCatalog: TaskCatalogEntry[] = [
  {
    id: 'classification',
    title: 'Supervised classification task',
    aliases: ['classification', 'categorization', 'label prediction'],
    strongSignals: ['class', 'classification', 'label', 'category'],
    supportSignals: ['binary', 'multiclass', 'target'],
    querySeeds: ['classification benchmark dataset'],
  },
  {
    id: 'regression',
    title: 'Continuous value prediction task',
    aliases: ['regression', 'value prediction', 'continuous target'],
    strongSignals: ['regression', 'predict', 'target value', 'continuous'],
    supportSignals: ['forecast', 'estimate', 'numeric target'],
    querySeeds: ['regression benchmark dataset'],
  },
  {
    id: 'anomaly-detection',
    title: 'Rare event or anomaly detection task',
    aliases: ['anomaly detection', 'fraud detection', 'rare event detection'],
    strongSignals: ['anomaly', 'fraud', 'rare', 'outlier'],
    supportSignals: ['imbalance', 'risk', 'sparse'],
    querySeeds: ['rare event detection benchmark'],
  },
  {
    id: 'time-series-forecasting',
    title: 'Time-series forecasting task',
    aliases: ['forecasting', 'time series forecasting', 'price prediction', 'market forecasting'],
    strongSignals: ['forecast', 'time series', 'historical', 'ohlcv', 'price'],
    supportSignals: ['return', 'volatility', 'rsi', 'macd', 'sequence'],
    querySeeds: ['time series forecasting dataset'],
  },
  {
    id: 'content-authenticity',
    title: 'Content authenticity or provenance task',
    aliases: ['content authenticity', 'ai vs human', 'generated text detection', 'provenance'],
    strongSignals: ['authenticity', 'generated', 'human', 'machine', 'provenance'],
    supportSignals: ['source', 'topic', 'language', 'style'],
    querySeeds: ['content authenticity classification dataset'],
  },
  {
    id: 'authorship-attribution',
    title: 'Authorship attribution task',
    aliases: ['authorship attribution', 'author identification', 'stylometry'],
    strongSignals: ['authorship', 'author', 'writer', 'style'],
    supportSignals: ['essay', 'writing', 'linguistic signature'],
    querySeeds: ['authorship attribution benchmark corpus'],
  },
];

export const modalityCatalog: ModalityCatalogEntry[] = [
  {
    id: 'tabular',
    title: 'Tabular dataset',
    aliases: ['table', 'structured table'],
    keywords: ['table', 'column', 'row'],
  },
  {
    id: 'text',
    title: 'Text-centric dataset',
    aliases: ['nlp', 'text', 'corpus'],
    keywords: ['text', 'content', 'prompt', 'document'],
  },
  {
    id: 'document',
    title: 'Document or prompt-response corpus',
    aliases: ['document corpus', 'prompt-response'],
    keywords: ['document', 'article', 'essay', 'response'],
  },
  {
    id: 'time-series',
    title: 'Temporal or time-series dataset',
    aliases: ['time series', 'temporal', 'historical'],
    keywords: ['date', 'timestamp', 'history', 'sequence'],
  },
  {
    id: 'transaction',
    title: 'Transaction dataset',
    aliases: ['transaction', 'payment event'],
    keywords: ['transaction', 'payment', 'merchant', 'card'],
  },
  {
    id: 'longitudinal',
    title: 'Longitudinal visit-based dataset',
    aliases: ['longitudinal', 'visit-level', 'cohort timeline'],
    keywords: ['visit', 'encounter', 'cohort', 'follow up'],
  },
];

export const knowledgeCatalog: KnowledgeCatalogEntry[] = [
  {
    id: 'kn-ai-text-detection-overview',
    title: 'AI-generated text detection overview and benchmark design notes',
    source: 'NLP survey digest',
    summary: 'Overview of human-vs-machine text detection, benchmark construction, and leakage risks.',
    kind: 'paper',
    tags: ['ai', 'generated', 'text', 'benchmark', 'human', 'machine', 'detection'],
    domainIds: ['dom-ai-generated-content-detection', 'dom-content-authenticity', 'dom-nlp'],
    publisher: 'Research survey collection',
    retrievalHint: 'Look for survey or benchmark overview material on generated text detection.',
    modality: 'text',
    taskSignals: ['classification', 'content-authenticity'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'kn-authorship-methods',
    title: 'Authorship attribution methods and stylistic feature guide',
    source: 'Methods review',
    summary: 'Covers stylometry, lexical features, prompt effects, and attribution caveats.',
    kind: 'paper',
    tags: ['authorship', 'writer', 'style', 'stylometry', 'language', 'text'],
    domainIds: ['dom-authorship-attribution', 'dom-nlp'],
    publisher: 'Computational linguistics review',
    retrievalHint: 'Use when searching authorship attribution or writing-style features.',
    modality: 'text',
    taskSignals: ['classification', 'authorship-attribution'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'kn-text-provenance',
    title: 'Text provenance and authenticity checklist',
    source: 'Trust and safety note',
    summary: 'Checklist for provenance metadata, source trust, and authenticity labeling decisions.',
    kind: 'guideline',
    tags: ['provenance', 'authenticity', 'source', 'trust', 'metadata'],
    domainIds: ['dom-content-authenticity', 'dom-misinformation-provenance'],
    publisher: 'Internal trust policy note',
    retrievalHint: 'Useful for provenance-aware authenticity work.',
    modality: 'text',
    taskSignals: ['classification', 'content-authenticity'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'kn-generated-text-bias',
    title: 'Bias and leakage risks in AI-vs-human text benchmarks',
    source: 'Benchmark analysis note',
    summary: 'Describes prompt leakage, model-family bias, and source imbalance in generated text corpora.',
    kind: 'paper',
    tags: ['bias', 'generated', 'human', 'benchmark', 'prompt', 'source'],
    domainIds: ['dom-ai-generated-content-detection', 'dom-content-authenticity'],
    publisher: 'Benchmark diagnostics collection',
    retrievalHint: 'Surface when the dataset has AI/human labels and prompt metadata.',
    modality: 'text',
    taskSignals: ['classification', 'content-authenticity'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'kn-writing-assessment',
    title: 'Educational writing assessment feature primer',
    source: 'Education analytics note',
    summary: 'Discusses prompt-response structure, readability, rubric features, and writing quality metrics.',
    kind: 'guideline',
    tags: ['essay', 'writing', 'prompt', 'response', 'rubric', 'readability'],
    domainIds: ['dom-education-writing-analysis', 'dom-text-classification'],
    publisher: 'Learning analytics handbook',
    retrievalHint: 'Useful when prompt, response, word_count, and complexity features are present.',
    modality: 'text',
    taskSignals: ['classification'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'kn-market-forecasting-overview',
    title: 'Financial time-series forecasting overview',
    source: 'Quant modeling note',
    summary: 'Overview of OHLCV feature engineering, horizon setup, and regression pitfalls in market prediction.',
    kind: 'paper',
    tags: ['stock', 'market', 'forecasting', 'ohlcv', 'price', 'volatility'],
    domainIds: ['dom-finance'],
    publisher: 'Quant research digest',
    retrievalHint: 'Use when the dataset contains OHLCV columns or market indicators.',
    modality: 'table',
    taskSignals: ['regression', 'time-series-forecasting'],
    modalitySignals: ['tabular', 'time-series'],
    negativeTags: ['prompt', 'essay', 'patient'],
  },
  {
    id: 'kn-technical-indicator-leakage',
    title: 'Technical indicator leakage and backtest caution note',
    source: 'Forecasting guideline',
    summary: 'Discusses rolling-window leakage, target shift, and improper indicator computation in price forecasting.',
    kind: 'guideline',
    tags: ['macd', 'rsi', 'leakage', 'backtest', 'forecast', 'return'],
    domainIds: ['dom-finance'],
    publisher: 'Applied forecasting handbook',
    retrievalHint: 'Helpful when RSI, MACD, volatility, or return columns are present.',
    modality: 'table',
    taskSignals: ['regression', 'time-series-forecasting'],
    modalitySignals: ['tabular', 'time-series'],
    negativeTags: ['prompt', 'content', 'patient'],
  },
  {
    id: 'kn-ich-e2a',
    title: 'ICH E2A clinical safety data management note',
    source: 'Guideline digest',
    summary: 'High level guideline on adverse event capture, coding, and reporting flow.',
    kind: 'guideline',
    tags: ['clinical', 'trial', 'adverse', 'patient', 'visit', 'safety'],
    domainIds: ['dom-medical'],
    modality: 'table',
    taskSignals: ['classification'],
    modalitySignals: ['tabular', 'longitudinal'],
    negativeTags: ['generated', 'authorship', 'language'],
  },
  {
    id: 'kn-faers-overview',
    title: 'FAERS reporting overview and sparse event caveats',
    source: 'Public knowledge note',
    summary: 'Overview of safety signal interpretation, duplicates, and reporting bias.',
    kind: 'wiki',
    tags: ['adverse', 'drug', 'reporting', 'sparse', 'imbalance'],
    domainIds: ['dom-medical'],
    modality: 'table',
    taskSignals: ['classification'],
    modalitySignals: ['tabular'],
    negativeTags: ['generated', 'content', 'prompt'],
  },
  {
    id: 'kn-biomarker-batch',
    title: 'Biomarker normalization and batch effect primer',
    source: 'Methods review',
    summary: 'Notes on assay drift, normalization, and batch effect handling for lab data.',
    kind: 'paper',
    tags: ['biomarker', 'assay', 'batch', 'protein', 'gene', 'lab'],
    domainIds: ['dom-bio'],
    modality: 'table',
    taskSignals: ['classification'],
    modalitySignals: ['tabular'],
    negativeTags: ['generated', 'authorship'],
  },
  {
    id: 'kn-fraud-threshold',
    title: 'Threshold tuning for imbalanced fraud detection',
    source: 'Applied ML practice note',
    summary: 'Precision recall tradeoffs, threshold tuning, and cost aware sparse label evaluation.',
    kind: 'paper',
    tags: ['fraud', 'transaction', 'threshold', 'imbalance', 'rare'],
    domainIds: ['dom-finance'],
    modality: 'table',
    taskSignals: ['classification', 'anomaly-detection'],
    modalitySignals: ['tabular', 'transaction'],
    negativeTags: ['prompt', 'content', 'language'],
  },
  {
    id: 'kn-predictive-maintenance',
    title: 'Predictive maintenance signal taxonomy',
    source: 'Industrial reliability handbook',
    summary: 'Vibration, temperature, and pressure based failure signatures.',
    kind: 'standard',
    tags: ['sensor', 'vibration', 'temperature', 'machine', 'equipment'],
    domainIds: ['dom-industrial'],
    modality: 'table',
    taskSignals: ['classification', 'anomaly-detection'],
    modalitySignals: ['tabular', 'time-series'],
    negativeTags: ['prompt', 'content', 'language'],
  },
  {
    id: 'kn-air-quality',
    title: 'Air quality monitoring QA and missing data guide',
    source: 'Monitoring guideline',
    summary: 'Station QA, sensor drift, threshold exceedance logic, and missing observation handling.',
    kind: 'guideline',
    tags: ['air', 'station', 'pollution', 'sensor', 'missing'],
    domainIds: ['dom-environment'],
    modality: 'table',
    taskSignals: ['classification'],
    modalitySignals: ['tabular', 'time-series'],
    negativeTags: ['prompt', 'content', 'authorship'],
  },
  {
    id: 'kn-public-policy',
    title: 'Regional bias checklist for public sector scoring',
    source: 'Government analytics checklist',
    summary: 'Checklist for agency and regional bias in public sector risk scoring workflows.',
    kind: 'guideline',
    tags: ['public', 'policy', 'region', 'agency', 'bias'],
    domainIds: ['dom-public'],
    modality: 'table',
    taskSignals: ['classification'],
    modalitySignals: ['tabular'],
    negativeTags: ['prompt', 'content', 'generated'],
  },
  {
    id: 'kn-missing-longitudinal',
    title: 'Repeated measure missingness and interpolation cautions',
    source: 'Statistics note',
    summary: 'Leakage risk and interpolation caveats for visit based datasets.',
    kind: 'guideline',
    tags: ['missing', 'visit', 'time', 'interpolation', 'imputation'],
    domainIds: ['dom-medical', 'dom-public'],
    modality: 'table',
    taskSignals: ['regression'],
    modalitySignals: ['tabular', 'longitudinal'],
    negativeTags: ['generated', 'authorship'],
  },
];

export const datasetCatalog: DatasetCatalogEntry[] = [
  {
    id: 'ds-hc3',
    name: 'HC3 human vs ChatGPT comparison corpus',
    provider: 'Hello-SimpleAI / Open benchmark',
    providerDetail: 'Human ChatGPT Comparison Corpus',
    description: 'Prompt-response text pairs labeled as human-written or ChatGPT-generated.',
    rowsHint: 'Tens of thousands of prompt-response pairs',
    modality: 'text with prompt-response fields',
    licenseHint: 'Benchmark terms vary by mirror',
    tags: ['ai', 'generated', 'human', 'prompt', 'response', 'text', 'chatgpt'],
    domainIds: ['dom-ai-generated-content-detection', 'dom-content-authenticity', 'dom-nlp'],
    retrievalHint: 'Strong fit for AI-vs-human text detection and prompt-response authenticity.',
    modalityType: 'text',
    sourceUrl: 'https://huggingface.co/datasets',
    taskSignals: ['classification', 'content-authenticity'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'ds-authorship-corpus',
    name: 'Authorship attribution benchmark corpus',
    provider: 'Stylometry benchmark collection',
    providerDetail: 'Author identification text corpus',
    description: 'Document-level corpus with author labels for writing style and attribution tasks.',
    rowsHint: 'Thousands of documents depending on subset',
    modality: 'labeled document corpus',
    licenseHint: 'Provider-specific benchmark terms',
    tags: ['authorship', 'author', 'style', 'document', 'text', 'writer'],
    domainIds: ['dom-authorship-attribution', 'dom-text-classification'],
    retrievalHint: 'Use when author labels, style metrics, or writing attribution are relevant.',
    modalityType: 'text',
    sourceUrl: 'https://huggingface.co/datasets',
    taskSignals: ['classification', 'authorship-attribution'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'ds-generated-text-detection',
    name: 'Generated text detection benchmark',
    provider: 'LLM detection benchmark',
    providerDetail: 'Human vs machine written content dataset',
    description: 'Benchmark corpus for distinguishing human-written and machine-generated text with metadata.',
    rowsHint: '10k to 100k labeled text rows',
    modality: 'text classification table',
    licenseHint: 'Benchmark mirror terms vary',
    tags: ['generated', 'human', 'machine', 'text', 'classification', 'metadata'],
    domainIds: ['dom-ai-generated-content-detection', 'dom-content-authenticity'],
    retrievalHint: 'Best fit when label values look like ai/human or generated/human.',
    modalityType: 'text',
    sourceUrl: 'https://huggingface.co/datasets',
    taskSignals: ['classification', 'content-authenticity'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'ds-multilingual-text-classification',
    name: 'Multilingual text classification benchmark',
    provider: 'NLP benchmark hub',
    providerDetail: 'Language-tagged text classification corpus',
    description: 'Text classification dataset with language metadata, topic labels, and multilingual documents.',
    rowsHint: 'Several benchmark splits',
    modality: 'multilingual text corpus',
    licenseHint: 'Benchmark-specific terms',
    tags: ['text', 'classification', 'language', 'topic', 'multilingual', 'document'],
    domainIds: ['dom-nlp', 'dom-text-classification'],
    retrievalHint: 'Useful when language and topic columns are prominent.',
    modalityType: 'text',
    sourceUrl: 'https://huggingface.co/datasets',
    taskSignals: ['classification'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'ds-writing-quality',
    name: 'Writing quality and prompt-response dataset',
    provider: 'Education analytics benchmark',
    providerDetail: 'Writing quality and rubric features corpus',
    description: 'Prompt-response writing samples with readability, length, and rubric-like auxiliary signals.',
    rowsHint: 'Thousands of essays or responses',
    modality: 'prompt-response writing corpus',
    licenseHint: 'Research benchmark terms',
    tags: ['essay', 'writing', 'prompt', 'response', 'readability', 'quality'],
    domainIds: ['dom-education-writing-analysis', 'dom-text-classification'],
    retrievalHint: 'Good match for prompt/content with word_count and complexity-style columns.',
    modalityType: 'text',
    sourceUrl: 'https://huggingface.co/datasets',
    taskSignals: ['classification'],
    modalitySignals: ['text', 'document'],
  },
  {
    id: 'ds-yahoo-ohlcv-history',
    name: 'Historical OHLCV market data archive',
    provider: 'Market data mirror',
    providerDetail: 'Daily OHLCV price history',
    description: 'Historical open, high, low, close, volume, and return-style financial market data for forecasting.',
    rowsHint: 'Thousands of daily rows per ticker',
    modality: 'financial time-series table',
    licenseHint: 'Provider-specific research terms',
    tags: ['stock', 'market', 'ohlcv', 'price', 'volume', 'return', 'forecast'],
    domainIds: ['dom-finance'],
    retrievalHint: 'Best fit when OHLCV, return, volatility, or market history columns exist.',
    modalityType: 'table',
    sourceUrl: 'https://finance.yahoo.com',
    taskSignals: ['regression', 'time-series-forecasting'],
    modalitySignals: ['tabular', 'time-series'],
    negativeTags: ['prompt', 'essay', 'patient'],
  },
  {
    id: 'ds-market-technical-indicators',
    name: 'Market technical indicator forecasting benchmark',
    provider: 'Quant benchmark hub',
    providerDetail: 'Price history with RSI, MACD, and volatility features',
    description: 'Financial time-series benchmark with OHLCV columns and derived technical indicators for regression.',
    rowsHint: 'Thousands to tens of thousands of time steps',
    modality: 'technical-indicator time series',
    licenseHint: 'Benchmark-specific terms',
    tags: ['market', 'rsi', 'macd', 'volatility', 'price', 'regression'],
    domainIds: ['dom-finance'],
    retrievalHint: 'Useful when MACD, RSI, or rolling volatility features are already present.',
    modalityType: 'table',
    sourceUrl: 'https://huggingface.co/datasets',
    taskSignals: ['regression', 'time-series-forecasting'],
    modalitySignals: ['tabular', 'time-series'],
    negativeTags: ['prompt', 'essay', 'clinical'],
  },
  {
    id: 'ds-mimic-demo',
    name: 'MIMIC III demo subset',
    provider: 'PhysioNet',
    providerDetail: 'Clinical ICU visit sample',
    description: 'Clinical patient visit table with vitals, labs, and outcome context.',
    rowsHint: '100 to 10000 rows depending on slice',
    modality: 'table (patient / visit)',
    licenseHint: 'Credential required for full dataset',
    tags: ['clinical', 'patient', 'vital', 'lab', 'visit'],
    domainIds: ['dom-medical'],
    retrievalHint: 'Clinical visit benchmark with patient and lab signals.',
    modalityType: 'table',
    sourceUrl: 'https://physionet.org',
    taskSignals: ['classification'],
    modalitySignals: ['tabular', 'longitudinal'],
    negativeTags: ['generated', 'authorship', 'prompt'],
  },
  {
    id: 'ds-synthea',
    name: 'Synthea synthetic cohort sample',
    provider: 'Synthea',
    providerDetail: 'Synthetic healthcare records',
    description: 'Synthetic patient visit, medication, and laboratory records.',
    rowsHint: '5000 to 50000 rows',
    modality: 'longitudinal visit log',
    licenseHint: 'Apache 2.0',
    tags: ['clinical', 'synthetic', 'visit', 'lab', 'cohort'],
    domainIds: ['dom-medical'],
    retrievalHint: 'Synthetic healthcare dataset with longitudinal visit structure.',
    modalityType: 'table',
    sourceUrl: 'https://synthetichealth.github.io/synthea/',
    taskSignals: ['classification'],
    modalitySignals: ['tabular', 'longitudinal'],
    negativeTags: ['generated text', 'authorship'],
  },
  {
    id: 'ds-credit-card-fraud',
    name: 'Credit card fraud detection benchmark',
    provider: 'Kaggle / ULB',
    providerDetail: 'Fraud detection transaction table',
    description: 'Sparse fraud labels on transaction level event data.',
    rowsHint: 'About 280k rows',
    modality: 'transaction table',
    licenseHint: 'Benchmark mirror terms vary',
    tags: ['fraud', 'transaction', 'payment', 'card', 'rare'],
    domainIds: ['dom-finance'],
    retrievalHint: 'Fraud benchmark for transaction-level anomaly detection.',
    modalityType: 'table',
    sourceUrl: 'https://www.kaggle.com',
    taskSignals: ['classification', 'anomaly-detection'],
    modalitySignals: ['tabular', 'transaction'],
    negativeTags: ['prompt', 'content', 'authorship'],
  },
  {
    id: 'ds-ieee-fraud',
    name: 'IEEE CIS fraud detection',
    provider: 'Kaggle',
    providerDetail: 'Transaction and identity fraud benchmark',
    description: 'Joined transaction and identity tables for fraud detection.',
    rowsHint: 'About 1M rows',
    modality: 'joined transaction and profile table',
    licenseHint: 'Competition terms apply',
    tags: ['fraud', 'transaction', 'identity', 'account'],
    domainIds: ['dom-finance'],
    retrievalHint: 'Large-scale fraud benchmark with transaction and identity joins.',
    modalityType: 'table',
    sourceUrl: 'https://www.kaggle.com',
    taskSignals: ['classification', 'anomaly-detection'],
    modalitySignals: ['tabular', 'transaction'],
    negativeTags: ['prompt', 'content', 'language'],
  },
  {
    id: 'ds-nasa-turbofan',
    name: 'NASA turbofan degradation simulation',
    provider: 'NASA',
    providerDetail: 'Predictive maintenance benchmark',
    description: 'Multivariate sensor sequences for equipment degradation and remaining life.',
    rowsHint: 'Train and test sequences',
    modality: 'multivariate sensor time series',
    licenseHint: 'Open benchmark',
    tags: ['sensor', 'machine', 'engine', 'temperature', 'pressure'],
    domainIds: ['dom-industrial'],
    retrievalHint: 'Predictive maintenance sensor benchmark.',
    modalityType: 'table',
    sourceUrl: 'https://www.nasa.gov',
    taskSignals: ['regression', 'time-series-forecasting'],
    modalitySignals: ['tabular', 'time-series'],
    negativeTags: ['prompt', 'content', 'authorship'],
  },
];
