import type {
  DatasetCatalogEntry,
  DomainCatalogEntry,
  KnowledgeCatalogEntry,
} from './contracts';

export const domainCatalog: DomainCatalogEntry[] = [
  {
    id: 'dom-medical',
    title: 'Medical clinical table for patient safety and outcome prediction',
    shortDescription:
      'Patient or visit level tables with vitals, labs, drug exposure, and safety or outcome labels.',
    keywords: ['patient', 'visit', 'clinical', 'hospital', 'drug', 'adverse', 'vital', 'lab'],
  },
  {
    id: 'dom-bio',
    title: 'Life science laboratory table for biomarker driven classification',
    shortDescription:
      'Assay, specimen, biomarker, or omics tables used for disease state or treatment response analysis.',
    keywords: ['biomarker', 'assay', 'specimen', 'protein', 'gene', 'omics', 'batch', 'lab'],
  },
  {
    id: 'dom-finance',
    title: 'Financial anomaly table for sparse event and fraud detection',
    shortDescription:
      'Transaction or account level event tables used for fraud, abuse, or suspicious behavior detection.',
    keywords: ['transaction', 'account', 'payment', 'merchant', 'fraud', 'transfer', 'card'],
  },
  {
    id: 'dom-industrial',
    title: 'Industrial sensor table for process and equipment monitoring',
    shortDescription:
      'Sensor driven process tables with temperature, pressure, vibration, or machine telemetry.',
    keywords: ['sensor', 'machine', 'equipment', 'vibration', 'temperature', 'pressure', 'rpm'],
  },
  {
    id: 'dom-environment',
    title: 'Environmental monitoring table for threshold breach detection',
    shortDescription:
      'Station or region level tables containing air, water, weather, or pollution observations.',
    keywords: ['air', 'water', 'weather', 'station', 'pollution', 'pm25', 'monitoring'],
  },
  {
    id: 'dom-public',
    title: 'Public sector table for regional or agency level risk prediction',
    shortDescription:
      'Administrative, demographic, or policy indicator tables used for public sector analytics.',
    keywords: ['region', 'city', 'district', 'policy', 'population', 'public', 'agency'],
  },
];

export const knowledgeCatalog: KnowledgeCatalogEntry[] = [
  {
    id: 'kn-ich-e2a',
    title: 'ICH E2A clinical safety data management note',
    source: 'Guideline digest',
    summary: 'High level guideline on adverse event capture, coding, and reporting flow.',
    kind: 'guideline',
    tags: ['clinical', 'trial', 'adverse', 'patient', 'visit', 'safety'],
  },
  {
    id: 'kn-faers-overview',
    title: 'FAERS reporting overview and sparse event caveats',
    source: 'Public knowledge note',
    summary: 'Overview of safety signal interpretation, duplicates, and reporting bias.',
    kind: 'wiki',
    tags: ['adverse', 'drug', 'reporting', 'sparse', 'imbalance'],
  },
  {
    id: 'kn-biomarker-batch',
    title: 'Biomarker normalization and batch effect primer',
    source: 'Methods review',
    summary: 'Notes on assay drift, normalization, and batch effect handling for lab data.',
    kind: 'paper',
    tags: ['biomarker', 'assay', 'batch', 'protein', 'gene', 'lab'],
  },
  {
    id: 'kn-fraud-threshold',
    title: 'Threshold tuning for imbalanced fraud detection',
    source: 'Applied ML practice note',
    summary: 'Precision recall tradeoffs, threshold tuning, and cost aware sparse label evaluation.',
    kind: 'paper',
    tags: ['fraud', 'transaction', 'threshold', 'imbalance', 'rare'],
  },
  {
    id: 'kn-predictive-maintenance',
    title: 'Predictive maintenance signal taxonomy',
    source: 'Industrial reliability handbook',
    summary: 'Vibration, temperature, and pressure based failure signatures.',
    kind: 'standard',
    tags: ['sensor', 'vibration', 'temperature', 'machine', 'equipment'],
  },
  {
    id: 'kn-air-quality',
    title: 'Air quality monitoring QA and missing data guide',
    source: 'Monitoring guideline',
    summary: 'Station QA, sensor drift, threshold exceedance logic, and missing observation handling.',
    kind: 'guideline',
    tags: ['air', 'station', 'pollution', 'sensor', 'missing'],
  },
  {
    id: 'kn-public-policy',
    title: 'Regional bias checklist for public sector scoring',
    source: 'Government analytics checklist',
    summary: 'Checklist for agency and regional bias in public sector risk scoring workflows.',
    kind: 'guideline',
    tags: ['public', 'policy', 'region', 'agency', 'bias'],
  },
  {
    id: 'kn-missing-longitudinal',
    title: 'Repeated measure missingness and interpolation cautions',
    source: 'Statistics note',
    summary: 'Leakage risk and interpolation caveats for visit based datasets.',
    kind: 'guideline',
    tags: ['missing', 'visit', 'time', 'interpolation', 'imputation'],
  },
];

export const datasetCatalog: DatasetCatalogEntry[] = [
  {
    id: 'ds-mimic-demo',
    name: 'MIMIC III demo subset',
    provider: 'PhysioNet',
    description: 'Clinical patient visit table with vitals, labs, and outcome context.',
    rowsHint: '100 to 10000 rows depending on slice',
    modality: 'table (patient / visit)',
    licenseHint: 'Credential required for full dataset',
    tags: ['clinical', 'patient', 'vital', 'lab', 'visit'],
  },
  {
    id: 'ds-synthea',
    name: 'Synthea synthetic cohort sample',
    provider: 'Synthea',
    description: 'Synthetic patient visit, medication, and laboratory records.',
    rowsHint: '5000 to 50000 rows',
    modality: 'longitudinal visit log',
    licenseHint: 'Apache 2.0',
    tags: ['clinical', 'synthetic', 'visit', 'lab', 'cohort'],
  },
  {
    id: 'ds-credit-card-fraud',
    name: 'Credit card fraud detection benchmark',
    provider: 'Kaggle / ULB',
    description: 'Sparse fraud labels on transaction level event data.',
    rowsHint: 'About 280k rows',
    modality: 'transaction table',
    licenseHint: 'Benchmark mirror terms vary',
    tags: ['fraud', 'transaction', 'payment', 'card', 'rare'],
  },
  {
    id: 'ds-ieee-fraud',
    name: 'IEEE CIS fraud detection',
    provider: 'Kaggle',
    description: 'Joined transaction and identity tables for fraud detection.',
    rowsHint: 'About 1M rows',
    modality: 'joined transaction and profile table',
    licenseHint: 'Competition terms apply',
    tags: ['fraud', 'transaction', 'identity', 'account'],
  },
  {
    id: 'ds-nasa-turbofan',
    name: 'NASA turbofan degradation simulation',
    provider: 'NASA',
    description: 'Multivariate sensor sequences for equipment degradation and remaining life.',
    rowsHint: 'Train and test sequences',
    modality: 'multivariate sensor time series',
    licenseHint: 'Open benchmark',
    tags: ['sensor', 'machine', 'engine', 'temperature', 'pressure'],
  },
  {
    id: 'ds-secom',
    name: 'SECOM manufacturing process data',
    provider: 'UCI ML Repository',
    description: 'High dimensional process measurements for manufacturing quality anomalies.',
    rowsHint: 'About 1500 rows',
    modality: 'process measurement table',
    licenseHint: 'UCI terms',
    tags: ['sensor', 'manufacturing', 'quality', 'process'],
  },
  {
    id: 'ds-air-quality',
    name: 'Air quality monitoring archive',
    provider: 'Public monitoring catalog',
    description: 'Station level pollution and weather observations.',
    rowsHint: 'Hourly records',
    modality: 'station time series',
    licenseHint: 'Public research use',
    tags: ['air', 'weather', 'station', 'pollution', 'monitoring'],
  },
  {
    id: 'ds-water-quality',
    name: 'Surface water quality measurements',
    provider: 'Public environmental catalog',
    description: 'Water quality sensor and sample measurements.',
    rowsHint: 'Thousands of records',
    modality: 'measurement table',
    licenseHint: 'Provider specific',
    tags: ['water', 'sensor', 'pollution', 'quality'],
  },
  {
    id: 'ds-public-health',
    name: 'Regional public health indicators',
    provider: 'Open government portal',
    description: 'Regional and agency level public health indicator table.',
    rowsHint: 'Annual regional aggregates',
    modality: 'regional statistics table',
    licenseHint: 'Open government terms',
    tags: ['public', 'region', 'agency', 'population'],
  },
];
